version: '2'
services:
  gallium:
    build: ./docker/gallium
    image: ubntintrepid/gallium:latest
    ports:
      - "3000:80"
      - "48895:22"
    volumes:
      - "./data/gallium:/data"
      - "./data/log/nginx:/var/log/nginx"
    links:
      - "db"
    env_file: .env

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
