version: '2'
services:
  gallium:
    build: ./docker/gallium
    image: ubntintrepid/gallium:latest
    ports:
      - "3000:80"
      - "48895:22"
    volumes:
      - "./data/gallium:/opt/gallium"
      - "./data/repositories:/data"
      - "./data/log/nginx:/var/log/nginx"
    links:
      - "db"
    env_file: .env

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"

  dev:
    build: ./docker/dev
    image: ubntintrepid/gallium-dev:latest
    links:
      - "db"
    env_file: .env
    volumes:
      - "./data/source:/source"
      - "./data/cargo_registry:/root/.cargo/registry"
      - "./data/gallium:/opt/gallium"
