version: '2'
services:
  gallium:
    build: .
    image: ubntintrepid/gallium:latest
    ports:
      - "48895:22"
    volumes:
      - "./bin:/opt/gallium/bin"
      - "./data/gallium:/data"
    links:
      - "db"
    environment:
      DATABASE_URL: postgres://postgres@db:5432/gallium

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    links:
      - "gallium"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/log/nginx:/var/log/nginx"

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
