// This file is automatically generated by diesel_cli.

table! {
    oauth_apps (id) {
        id -> Int4,
        name -> Text,
        created_at -> Timestamp,
        client_id -> Varchar,
        redirect_uri -> Text,
    }
}

table! {
    projects (id) {
        id -> Int4,
        created_at -> Timestamp,
        user_id -> Int4,
        name -> Text,
        description -> Text,
    }
}

table! {
    public_keys (id) {
        id -> Int4,
        created_at -> Timestamp,
        key -> Text,
        user_id -> Int4,
        title -> Text,
    }
}

table! {
    users (id) {
        id -> Int4,
        name -> Text,
        email_address -> Text,
        bcrypt_hash -> Text,
        created_at -> Timestamp,
        screen_name -> Text,
        is_admin -> Bool,
    }
}
