// This file is automatically generated by diesel_cli.

table! {
    projects (id) {
        id -> Int4,
        created_at -> Timestamp,
        user_id -> Int4,
        name -> Text,
        description -> Nullable<Text>,
    }
}

table! {
    ssh_keys (id) {
        id -> Int4,
        created_at -> Timestamp,
        key -> Text,
        user_id -> Int4,
        description -> Nullable<Text>,
    }
}

table! {
    users (id) {
        id -> Int4,
        created_at -> Timestamp,
        name -> Text,
        screen_name -> Nullable<Text>,
        bcrypt_hash -> Varchar,
    }
}
