// This file is automatically generated by diesel_cli.

table! {
    public_keys (id) {
        id -> Int4,
        created_at -> Timestamp,
        key -> Text,
        user_id -> Int4,
        title -> Text,
    }
}

table! {
    users (id) {
        id -> Int4,
        username -> Text,
        email_address -> Text,
        bcrypt_hash -> Text,
        created_at -> Timestamp,
    }
}
